config/routes.rb
Myflix::Application.routes.draw do
 
  
  root to: 'pages#front'
  get '/home', to: 'videos#index'
    
  resources :videos, only: [:show] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end
  
  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end
  
  get 'ui(/:action)', controller: 'ui'
  get '/register', to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get 'my_queue', to: 'queue_items#index'
  
  resources :users, only: [:show, :create, :edit, :update]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]
  
  resources :categories, only: [:new, :create, :show]
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'
  
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
  
  resources :invitations, only: [:new, :create]
 
  mount StripeEvent::Engine => 'stripe_events'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
  belongs_to :leader, class_name: 'User', foreign_key: 'leader_id'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :require_user
  def index
    @relationships = current_user.following_relationships
  end
  
  def create
    leader = User.find(params[:leader_id])
    Relationship.create(leader_id: params[:leader_id], follower: current_user) unless current_user.follows?(leader) || current_user == leader
    redirect_to people_path
  end
  
  def destroy
    relationship = Relationship.find(params[:id])
    relationship.destroy if relationship.follower == current_user
    redirect_to people_path   
  end
end

app/views/relationships/index.html.haml
%section.people
  %header
    %h2 People I Follow
    %br
    %h4= link_to "Click here to invite a friend to MyFlix", new_invitation_path
  %table.table
    %thead
      %tr
        %th(width="30%")
        %th(width="20%") Videos in Queue
        %th(width="20%") Followers
        %th(width="30%") Unfollow
    %tbody
      - @relationships.each do |relationship|

        %tr
          %td
            %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(relationship.leader.email.downcase)}?s=40")
            = link_to relationship.leader.name, relationship.leader
          %td.extra-padding= relationship.leader.queue_items.count
          %td.extra-padding= relationship.leader.leading_relationships.count
          %td.extra-padding
            = link_to relationship, :method => 'delete' do 
              %i.glyphicon.glyphicon-remove