config/routes.rb
Myflix::Application.routes.draw do
 
  
  root to: 'pages#front'
  get '/home', to: 'videos#index'
    
  resources :videos, only: [:show] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end
  
  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end
  
  get 'ui(/:action)', controller: 'ui'
  get '/register', to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get 'my_queue', to: 'queue_items#index'
  
  resources :users, only: [:show, :create, :edit, :update]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]
  
  resources :categories, only: [:new, :create, :show]
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'
  
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
  
  resources :invitations, only: [:new, :create]
 
  mount StripeEvent::Engine => 'stripe_events'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, -> { order(created_at: :desc) }
  has_many :queue_items, -> { order(position: :asc, updated_at: :desc) }
  has_many :following_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :leading_relationships, class_name: "Relationship", foreign_key: :leader_id
  
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
  
  has_secure_password validations: false
  
  #before_create :generate_token  #the call to generate_token was moved to forgot_passwords_controller#create
  
  def normalize_queue_item_positions
    queue_items.each_with_index do |queue_item, index|
      queue_item.update_attributes(position: index+1)
    end
  end
  
  def queued_video?(video)
    queue_items.map(&:video).include?(video)
  end
  
  def follows?(another_user)
    following_relationships.map(&:leader).include?(another_user)
  end
  
  def follow(another_user)
    following_relationships.create(leader: another_user) if can_follow?(another_user)
  end
  
  def can_follow?(another_user)
    !(self.follows?(another_user) || self == another_user)
  end
  
  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end
  
  def deactivate!
    update_column(:active, false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    result = UserSignup.new(@user).sign_up(params[:stripeToken], params[:invitation_token])
    if result.successful?   
      flash[:success] = "Thank you for registering with MyFlix. Please sign in now."
      redirect_to login_path
    else
      flash[:error] = result.error_message
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new_with_invitation_token
    invitation = Invitation.where(token: params[:token]).first
    if invitation
      @user = User.new(email: invitation.recipient_email)
      @invitation_token = invitation.token
      render :new
    else
      redirect_to expired_token_path
    end
  end


private
  def user_params
    params.require(:user).permit(:name, :password, :email, :password_confirmation)
  end
  
end

app/views/users/new.html.haml
%script{:src => "https://js.stripe.com/v2/", :type => "text/javascript"}
:javascript
  Stripe.setPublishableKey('#{ENV['STRIPE_PUBLISHABLE_KEY']}');

= javascript_include_tag 'payment'
%section.register.container
  .row
    .col-sm-10.col-sm-offset-1
      .form-horizontal
        = bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-6", html: {id: "payment-form"}) do |f|
          %header
            %h1 Register
          %fieldset
            = f.email_field :email, label: "Email Address"
            = f.password_field :password
            = f.password_field :password_confirmation, label: "Confirm Password" 
            = f.text_field :name, label: "Full Name"
            = hidden_field_tag :invitation_token, @invitation_token
          %fieldset.credit_card
            .payment-errors
            .form-group
              %label.control-label.col-sm-2(for="credit-card-number") Credit Card Number
              .col-sm-6
                %input.form-control#credit-card-number(type="text" data-stripe="number")
            .form-group
              %label.control-label.col-sm-2(for="security-code") Security Code
              .col-sm-6
                %input.form-control#security-code(type="text" data-stripe="cvc")
            .form-group
              %label.control-label.col-sm-2 Expiration
              .col-sm-3
                = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: {stripe: "exp-month"})
              .col-sm-2
                = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: "exp-year"})

              -#<script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key=#{ENV['STRIPE_PUBLISHABLE_KEY']} data-name="Pay for MyFlix Now" data-description="$9.99 to sign up for MyFlix video streaming" data-amount="999"></script>            
            %fieldset.actions.control-group.col-sm-offset-2
              .controls
                %input(type="submit" value="Sign Up" class="btn btn-default")
.row
  .col-sm-10.col-sm-offset-1
    %p#fake-register Thank you for visiting. This application is currently in demo mode. Feel free to explore by using the fake credit card number '4242424242424242' to register.  You can make up any 3-digit security code and future expiration date. Please DO NOT use a real credit card number.  Upon registration a fake charge of $9.99 will be issued against the fake credit card number.  Please be aware that your video queue may be visible to other users. If using a fake email address, we recommend using @example.com. Registering an email address will result in a welcome mail sent to that address. 
.row
  #foot
    %p= "Coded by Ashlynn Pai. Copyright #{Time.now.year}"

app/views/users/show.html.haml
%section.user.container
  .row
    .col-sm-10.col-sm-offset-1
      %article
        %header
          -# %img(src="http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(@user.email.downcase)}?s=40")
          %h2 #{@user.name}'s video collections (#{@user.queue_items.count})
          
          = button_to "Follow", relationships_path(leader_id: @user.id), :class => 'btn', :id => 'follow-btn', :method => 'post' unless @user == current_user || current_user.follows?(@user)
        %table.table
          %thead
            %tr
              %th(width="30%") Video Title
              %th(width="15%") Genre
          %tbody
            - @user.queue_items.each do |queue_item| 
              %tr
                %td
                  = link_to queue_item.video.title, video_path(queue_item.video)
                %td
                  = link_to queue_item.category.name, category_path(queue_item.category)

%section.user_reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      %header
        %h3 #{@user.name}'s Reviews (#{@user.reviews.count})
      %ul
        - @user.reviews.each do |review|
          %article.review
            %li.row
              .col-sm-2
                %p
                  = link_to review.video.title, video_path(review.video)
                %col= "Rating: #{review.rating}"
              .col-sm-8
                %p= review.content