config/routes.rb
Myflix::Application.routes.draw do
 
  
  root to: 'pages#front'
  get '/home', to: 'videos#index'
    
  resources :videos, only: [:show] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end
  
  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end
  
  get 'ui(/:action)', controller: 'ui'
  get '/register', to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get 'my_queue', to: 'queue_items#index'
  
  resources :users, only: [:show, :create, :edit, :update]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]
  
  resources :categories, only: [:new, :create, :show]
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'
  
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
  
  resources :invitations, only: [:new, :create]
 
  mount StripeEvent::Engine => 'stripe_events'
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category
  has_many :reviews, -> { order 'created_at DESC' }
  has_many :queue_items
  
  mount_uploader :large, LargeCoverUploader
  mount_uploader :small, SmallCoverUploader
  
  validates :title, presence: true
  validates :description, presence: true
  
  def self.search_by_title(search_term)
    return [] if search_term.blank?
    where("title ILIKE ?", "%#{search_term}%").order("created_at DESC")
  end
  
  def rating
    reviews.average(:rating).round(1) if reviews.average(:rating)
  end  
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < AdminsController
  before_filter :require_user
  before_filter :ensure_admin  #defined in admins_controller.rb
  
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.create(video_params)
    if @video.save
      flash[:success] = "You have added '#{@video.title}'."
      redirect_to new_admin_video_path
    else
      flash[:error] = "The video was not added."
      render :new
    end
  end
  
  private
  
  def video_params
    params.require(:video).permit(:title, :description, :category_id, :small, :large, :video_url)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :require_user
  
  def index
    @categories = Category.all
  end
  
  def show
    @video = VideoDecorator.decorate(Video.find(params[:id]))
    @reviews = @video.reviews
    @review = Review.new
  end
  
  def search
    @results = Video.search_by_title(params[:search_term]) 
  end

  private

    
end

app/views/videos/index.html.haml
- @categories.each do |category|
  .category-row
    %h1= link_to category.name, category_path(category)
    - category.recent_videos.each do |video|
      .each-video
        = link_to image_tag(video.small, width: '140'), video_path(video)
  

app/views/videos/search.html.haml
- @results.each do |video|
  = link_to image_tag(video.small, width: '140'), video_path(video)

  

app/views/videos/show.html.haml
%article.video
  .container
    .row
      .video_large_cover.col-sm-7.col-sm-offset-1
        = image_tag(@video.large, width: '300')
      .video_info.col-sm-3
        %header
          %p#video-title= @video.title
          %span Rating: 
          = @video.rating
        %p= @video.description
        .actions
          = link_to 'Watch Now', @video.video_url, class: "btn btn-primary"
          = link_to "+ My Queue", queue_items_path(video_id: @video.id), method: :post, class: 'btn btn-primary' unless current_user.queued_video?(@video)

%section.reviews.container
  .row
    .col-sm-10.col-sm-offset-1
      = form_for [@video, Review.new] do |f|
        %fieldset
          .form-group
            %label Rate this video
            = f.select :rating, options_for_video_reviews
          .form-group
            %label Write Review
            %br
            =f.text_area :content, rows: 6, class: "col-sm-6" 
        %fieldset.form-group.actions.clearfix
          %input(type="submit" value="Submit" class="btn")
          = link_to "Cancel", @video
      %header
        %h3 User Reviews (#{@reviews.count})
      %ul
        - @reviews.each do |review| 
          %article.review
            %li.row
              .col-sm-2
                %span Rating: #{review.rating}
                %p= link_to review.user.name, user_path(review.user)
              .col-sm-8
                %p= review.content