config/routes.rb
Myflix::Application.routes.draw do
 
  
  root to: 'pages#front'
  get '/home', to: 'videos#index'
    
  resources :videos, only: [:show] do
    collection do
      get :search, to: "videos#search"
    end
    resources :reviews, only: [:create]
  end
  
  namespace :admin do
    resources :videos, only: [:new, :create]
    resources :payments, only: [:index]
  end
  
  get 'ui(/:action)', controller: 'ui'
  get '/register', to: 'users#new'
  get 'register/:token', to: "users#new_with_invitation_token", as: 'register_with_token'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  get 'my_queue', to: 'queue_items#index'
  
  resources :users, only: [:show, :create, :edit, :update]
  get 'people', to: 'relationships#index'
  resources :relationships, only: [:create, :destroy]
  
  resources :categories, only: [:new, :create, :show]
  resources :queue_items, only: [:create, :destroy]
  post 'update_queue', to: 'queue_items#update_queue'
  
  get 'forgot_password', to: 'forgot_passwords#new'
  resources :forgot_passwords, only: [:create]
  get 'forgot_password_confirmation', to: 'forgot_passwords#confirm'
  
  resources :password_resets, only: [:show, :create]
  get 'expired_token', to: 'pages#expired_token'
  
  resources :invitations, only: [:new, :create]
 
  mount StripeEvent::Engine => 'stripe_events'
end

app/views/shared/_header.html.haml
%section#top-header.row
  %h1.col-md-2
    .header-title
      = link_to "MYFLIX", home_path
  - if current_user    
    %ul.col-md-4.clearfix.menu-item
      %li= link_to "Videos", home_path
      %li= link_to "My Queue", my_queue_path
      %li= link_to "People", people_path
  - else
    %ul.col-md-4.clearfix
      %li= link_to "Register", register_path

  .col-md-5.for-search
    = form_tag search_videos_path, :method => 'get' do 
      = text_field_tag :search_term, nil, class: 'form-control', placeholder: 'Search for videos'
      = submit_tag "Search", :class => 'btn'
  #user_links.pull-right
    %ul
      %li.dropdown
        %a(href="#" id="dlabel" role="button" data-toggle="dropdown" class="dropdown-toggle" data-target="#")
          - if current_user    
            Welcome, #{current_user.name}
            %b.caret
          %ul.dropdown-menu(role="menu" aria-labelledby="dlabel")
            %li
              %a(href="#") Account
              %a(href="#") Plan and Billing
              = link_to "Sign Out", logout_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)